[build]
  command = "npm run build"
  publish = "dist"
  functions = ".netlify/functions-internal"

[dev]
  command = "npm run dev"
  port = 4321

[functions]
  node_bundler = "esbuild"
  included_files = ["dist/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/entry"
  status = 200